const friends=[
    
    {id:1,
        name:"Grég",
        adresse:"rue du tour",
        n:245,cp:66,
        ville:"Route 66",
        pays:"USA",
        passions:[1,3,5],
        photo:"greg.jpg", 
        cover:"greg-cover.jpg",
        adress:"greg@gmail.com"},
    
    {id:2,
        name:"Amant",
        adresse:"voie du cours ",
        n:567,
        cp:1050,
        ville:"Saint-Ghislain",
        pays:"Espace",
        passions:[1,2,4],
        photo:"amant.jpg", 
        cover:"amant-cover.jpg",
        adress:"amant@gmail.com"},
    
    {id:3,
        name:"Vincenzo",
        adresse:"voie Berthe ",
        n:199,
        cp:7020,
        ville:"Prison",
        pays:"Azkaban",
        passions:[8,7,5],
        photo:"vincenzo.jpg", 
        cover:"vincenzo-cover.jpg",
        adress:"vincenzo@gmail.com"},
    
    {id:4,
        name:"Amaury",
        adresse:"sous l'eau",
        n:19,
        cp:8520,
        ville:"Genéve",
        pays:"Suisse",
        passions:[1,2,4],
        photo:"amaury.jpg", 
        cover:"amaury-cover.jpg",
        adress:"amaury@gmail.com"},
    
    {id:5,
        name:"Franck",
        adresse:"faille de l'invocateur",
        n:87,
        cp:185,
        ville:"Ionia",
        pays:"USA",
        passions:[4,2,8],
        photo:"franck.jpg", 
        cover:"franck-cover.jpg",
        adress:"franck@gmail.com"},
    
    {id:6,
        name:"Adrien",
        adresse:"carte mere",
        n:45,
        cp:1236,
        ville:"ordinateur",
        pays:"belgique",
        passions:[7,6,9],
        photo:"adrien.jpg", 
        cover:"adrien-cover.jpg",
        adress:"adrien@gmail.com"},
    
    {id:7,
        name:"Denis",
        adresse:"East blue",
        n:852,
        cp:174,
        ville:"Fushia",
        pays:"Grand line",
        passions:[9,2,4],
        photo:"denis.jpg", 
        cover:"denis-cover.jpg",
        adress:"denis@gmail.com"},
    
    {id:8,
        name:"Maxime",
        adresse:"avenue marchand",
        n:199,
        cp:7020,
        ville:"Concessionnaire",
        pays:"Italie",
        passions:[8,2,4],
        photo:"maxime.jpg", 
        cover:"maxime-cover.jpg",
        adress:"maxime@gmail.com"},
    
    {id:9,
        name:"Steve",
        adresse:"Silicon valley",
        n:854,
        cp:7624,
        ville:"Hyon",
        pays:"USA",
        passions:[1,7,3],
        photo:"steve.jpg", 
        cover:"steve-cover.jpg",
        adress:"steve@gmail.com"},
    
    {id:10,
        name:"Redha",
        adresse:"villa madrigal",
        n:854,
        cp:7624,
        ville:"Hyon",
        pays:"Belgique",
        passions:[1,8,6],
        photo:"redha.jpg", 
        cover:"redha-cover.jpg",
        adress:"redha@gmail.com"},
    
    {id:11,
        name:"Bruno",
        adresse:"villa madrigal",
        n:854,
        cp:7624,
        ville:"oui",
        pays:"Mexique",
        passions:[1,3,6],
        photo:"bruno.jpg", 
        cover:"bruno-cover.jpg",
        adress:"bruno@gmail.com"},
    
    {id:12,
        name:"Audrey",
        adresse:"Dans les bois",
        n:854,
        cp:7624,
        ville:"Disneyland",
        pays:"USA",
        passions:[1,4,2],
        photo:"audrey.jpg", 
        cover:"audrey-cover.jpg",
        adress:"audrey@gmail.com"},
];

const passions = [
    
    {id:1,
        title:"Football", 
        description:"Je suis un garçon très sérieux. Je suis une personne très responsable dans la vie. J'aime le sport, surtout le football et le basketball."},
    
    {id:2,
        title:"Cinema", 
        description:"Le cinéma me fait vibrer, fait briller mes yeux et m’apporte tant de choses, d’émotions. Il rend ma vie plus douce, et je m’endors souvent en me remémorant certaines scènes des films que je viens de visionner, ou de mes films préférés."},

    {id:3,
        title:"Lecture", 
        description:"Je pourrai passer tout mon temps à lire, j'ai appris il n'y a pas très longtemps qu'il y a plusieurs sorte de lecteurs, ceux qui lisent pour s'instruire, ceux qui lisent de temps en temps par plaisir et ceux qui lisent parce qu'ils en ont besoin, un peu comme une drogue eh bien je crois que je suis dans cette dernière catégorie "},

    {id:4,
        title:"Restaurants", 
        description:"Les truites élevées dans les eaux cristallines des ruisseaux ardennais sont un des classiques de la gastronomie locale. En automne, c’est la saison du gibier: faisan, chevreuil et sanglier sont alors au menu. Le jambon d’Ardenne se fait aussi dans la région et une visite des salaisons est quasi incontournable."},

    {id:5,
        title:"City trips", 
        description:"C'est évidemment nettement plus long, je vous le concède. Mais vous continuez ainsi à parler français et non anglais. Concrètement il s'agit d'un séjour de courte durée à teneur touristique, organisé pour découvrir un maximum de hauts lieux d'une ville."},

    {id:6,
        title:"La drogue", 
        description:"La cocaïnomanie est la dépendance à la cocaïne. Quels sont les symptômes d'un cocaïnomane ? Comment aider une personne atteinte de cette addiction ? Toutes les réponses à vos questions se trouvent dans la fiche complète ci-dessous."},

    {id:7,
        title:"Gaming", 
        description:"Le phénomène est généralement décrit comme une perte de contrôle temporaire du comportement de jeu, lié à de la colère et à de la frustration - « C’est la perte de contrôle, sous le coup d’une colère démesurée, qui emmène une perte de contrôle sur soi, liée à certains événements du jeu, à un manque de maîtrise, etc. »"},

    {id:8,
        title:"La prostitution", 
        description:"En Belgique, bien que la prostitution ne soit pas une activité illégale en soi,elle s'exerce souvent dans un contexte d'illégalité et de clandestinité.  Dans la pratique, la limite entre prostitution légale et illégale est parfois floue."},

    {id:9,
        title:"manger du pain", 
        description:"Le pain au levain est un pain fait à base de levain, c'est-à-dire d'un mélange d'eau et de farine où se développe une culture de levure et de bactérie lactique. La farine est fermentée par cette culture. Cette fermentation, en dégageant du dioxyde de carbone, permet à la pâte de lever."},
]
